In [6]:
#RNN
from tensorflow.keras.layers import SimpleRNN,Embedding,Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
import numpy as np


In [13]:
vocab_size=5000
(x_train,y_train),(x_test,y_test)=imdb.load_data(num_words=vocab_size)
x_train=sequence.pad_sequences(x_train,maxlen=80)
x_test=sequence.pad_sequences(x_test,maxlen=80)
print(x_train)

model=Sequential()
model.add(Embedding(5000,128))
model.add(SimpleRNN(128,activation='tanh',return_sequences=False))
model.add(Dense(1,activation="sigmoid"))
model.build(input_shape=None)
model.summary()
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=3,batch_size=32,validation_data=(x_test,y_test),shuffle=True)
model.summary()
op=model.predict(x_test)
op
from random import randint
arr_ind=randint(0,24999)
index=imdb.get_word_index()

reverse_index = dict([(value, key) for (key, value) in index.items()])
decoded = " ".join([reverse_index.get(i - 3, "#") for i in x_test[arr_ind]])
arr=[]

for i in op:
  if(i<0.5):
    arr.append("Negative")
  else:
    arr.append("Positive")

print("Sentence:",decoded)
print("Review:",arr[arr_ind])
print("Predicted Value:",op[arr_ind][0])
print("Expected Value:",y_test[arr_ind])

[[  15  256    4 ...   19  178   32]
 [ 125   68    2 ...   16  145   95]
 [ 645  662    8 ...    7  129  113]
 ...
 [ 529  443    2 ...    4 3586    2]
 [ 286 1814   23 ...   12    9   23]
 [  97   90   35 ...  204  131    9]]


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/3
782/782 ━━━━━━━━━━━━━━━━━━━━ 29s 32ms/step - accuracy: 0.5842 - loss: 0.6536 - val_accuracy: 0.7990 - val_loss: 0.4482
Epoch 2/3
782/782 ━━━━━━━━━━━━━━━━━━━━ 24s 31ms/step - accuracy: 0.8086 - loss: 0.4277 - val_accuracy: 0.7313 - val_loss: 0.5359
Epoch 3/3
782/782 ━━━━━━━━━━━━━━━━━━━━ 26s 33ms/step - accuracy: 0.8125 - loss: 0.4323 - val_accuracy: 0.7818 - val_loss: 0.4613


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 80, 128)        │       640,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,019,077 (7.70 MB)

 Trainable params: 673,025 (2.57 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,346,052 (5.13 MB)

782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step


array([[0.4777098 ],
       [0.9110258 ],
       [0.32320738],
       ...,
       [0.5857657 ],
       [0.12574966],
       [0.761366  ]], dtype=float32)

Sentence: points where the plot # and leaves some confusion also after building to a tense climax the ending is something of a let down the supporting characters were # weak the alien hunter or menacing the psychiatrist which also served to # br br but all in all it raised some interesting issues amongst which was a telling line how do think animals feel when we experiment on them br br the concept of lost time was also thought provoking
Review: Positive
Predicted Value: 0.6061908
Expected Value: 1


In [ ]:
from tensorflow.keras.layers import SimpleRNN, LSTM, GRU, Bidirectional, Dense, Embedding
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
import numpy as np


# Getting reviews with words that come under 5000
# most occurring words in the entire
# corpus of textual review data
vocab_size = 5000
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

print(x_train[0])

# Getting all the words from word_index dictionary
word_idx = imdb.get_word_index()

# Originally the index number of a value and not a key,
# hence converting the index as key and the words as values
word_idx = {i: word for word, i in word_idx.items()}

# again printing the review
print([word_idx[i] for i in x_train[0]])

# Get the minimum and the maximum length of reviews
print("Max length of a review:: ", len(max((x_train+x_test), key=len)))
print("Min length of a review:: ", len(min((x_train+x_test), key=len)))

from tensorflow.keras.preprocessing import sequence

# Keeping a fixed length of all reviews to max 400 words
max_words = 400

x_train = sequence.pad_sequences(x_train, maxlen=max_words)
x_test = sequence.pad_sequences(x_test, maxlen=max_words)

x_valid, y_valid = x_train[:64], y_train[:64]
x_train_, y_train_ = x_train[64:], y_train[64:]
# fixing every word's embedding size to be 32
embd_len = 32

# Creating a RNN model
RNN_model = Sequential(name="Simple_RNN")
RNN_model.add(Embedding(vocab_size,
						embd_len,
						input_length=max_words))

# In case of a stacked(more than one layer of RNN)
# use return_sequences=True
RNN_model.add(SimpleRNN(128,
						activation='tanh',
						return_sequences=False))
RNN_model.add(Dense(1, activation='sigmoid'))

# Building the model by running a dummy input
RNN_model.build(input_shape=(None, max_words))

# printing model summary
print(RNN_model.summary())

# Compiling model
RNN_model.compile(
	loss="binary_crossentropy",
	optimizer='adam',
	metrics=['accuracy']
)

# Training the model
history = RNN_model.fit(x_train_, y_train_,
						batch_size=64,
						epochs=5,
						verbose=1,
						validation_data=(x_valid, y_valid))

# Printing model score on test data
print()
print("Simple_RNN Score---> ", RNN_model.evaluate(x_test, y_test, verbose=0))


[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 2, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 2, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 2, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 2, 19, 178, 32]
['the', 'as', 'you', 'with', 'out', 'themselves', 'powerful', 'lets', 'love

C:\Users\KIRTAN\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "Simple_RNN"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 400, 32)        │       160,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 128)            │        20,608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 180,737 (706.00 KB)

 Trainable params: 180,737 (706.00 KB)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/5
390/390 ━━━━━━━━━━━━━━━━━━━━ 42s 98ms/step - accuracy: 0.5492 - loss: 0.6784 - val_accuracy: 0.6719 - val_loss: 0.6082
Epoch 2/5
390/390 ━━━━━━━━━━━━━━━━━━━━ 38s 97ms/step - accuracy: 0.7714 - loss: 0.4821 - val_accuracy: 0.8438 - val_loss: 0.4275
Epoch 3/5
390/390 ━━━━━━━━━━━━━━━━━━━━ 41s 104ms/step - accuracy: 0.7559 - loss: 0.5109 - val_accuracy: 0.6719 - val_loss: 0.5232
Epoch 4/5
390/390 ━━━━━━━━━━━━━━━━━━━━ 45s 114ms/step - accuracy: 0.8302 - loss: 0.3872 - val_accuracy: 0.8750 - val_loss: 0.3662
Epoch 5/5
179/390 ━━━━━━━━━━━━━━━━━━━━ 25s 121ms/step - accuracy: 0.7609 - loss: 0.4861

In [ ]:
from tensorflow.keras.layers import SimpleRNN, Dense, Embedding, Dropout
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np
import matplotlib.pyplot as plt

# Load IMDB dataset with a vocabulary size of 5000
vocab_size = 5000
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

# Get the word index to decode reviews (optional, for understanding the data)
word_idx = imdb.get_word_index()
word_idx = {i: word for word, i in word_idx.items()}  # Reverse the word index

# Print the first review (as words) to understand the data
print([word_idx.get(i - 3, "<unk>") for i in x_train[0]])

# Check the max and min length of reviews
print(f"Max length of a review: {len(max((x_train + x_test), key=len))}")
print(f"Min length of a review: {len(min((x_train + x_test), key=len))}")

# Pad sequences to make all reviews of equal length (400 words)
max_words = 400
x_train = sequence.pad_sequences(x_train, maxlen=max_words)
x_test = sequence.pad_sequences(x_test, maxlen=max_words)

# Split off a small part of the training data for validation
x_valid, y_valid = x_train[:64], y_train[:64]
x_train_, y_train_ = x_train[64:], y_train[64:]

# Set the embedding dimension and define the model
embd_len = 32

RNN_model = Sequential(name="Simple_RNN_with_Dropout")
RNN_model.add(Embedding(vocab_size, embd_len, input_length=max_words))
RNN_model.add(SimpleRNN(128, activation='tanh'))  # RNN layer
RNN_model.add(Dropout(0.5))  # Dropout layer to prevent overfitting
RNN_model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

# Compile the model
RNN_model.compile(
    loss="binary_crossentropy",
    optimizer='adam',
    metrics=['accuracy']
)

# EarlyStopping callback to stop training when validation loss stops improving
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# Train the model
history = RNN_model.fit(
    x_train_, y_train_,
    batch_size=64,
    epochs=10,
    verbose=1,
    validation_data=(x_valid, y_valid),
    callbacks=[early_stopping]
)

# Evaluate the model on the test data
test_loss, test_accuracy = RNN_model.evaluate(x_test, y_test, verbose=0)
print(f"\nTest Loss: {test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}")

# Plotting the training and validation loss and accuracy
def plot_history(history):
    # Accuracy Plot
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', marker='o')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy', marker='o')
    plt.title('Model Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()

    # Loss Plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', marker='o')
    plt.plot(history.history['val_loss'], label='Validation Loss', marker='o')
    plt.title('Model Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

# Call the function to plot the history
plot_history(history)

